const mongoose = require('mongoose');

const externalIntegrationConfigSchema = new mongoose.Schema({
    retailer: { type: mongoose.Schema.Types.ObjectId, ref: 'RetailerProfile', required: true },
    type: {
        type: String,
        enum: ['WEBHOOK', 'FILE_UPLOAD', 'API_POLLING'],
        required: true
    },
    vendorName: { type: String }, // e.g., "Tally", "Busy"
    apiKey: { type: String }, // Generated by us
    sharedSecret: { type: String },
    isActive: { type: Boolean, default: true },
    lastSyncedAt: { type: Date }
}, { timestamps: true });

module.exports = mongoose.model('ExternalIntegrationConfig', externalIntegrationConfigSchema);
